### ISSUE TITLE
팔로우회원들의 글목록

### ISSUE THREAD

**Issue by wookho** [ramboclouds/xe-something#10]
보안상의 문제로 내 팔로우의 명단을 공개할 수 없는 경우가 많습니다.

배포 전에 의견으로 드렸던

회원 각자가 스스로 자신이 팔로우 해 놓은 회원들의 글 목록을 보려면 
관리자가 어떤 링크를 제공해야 하는지 알려주시면 좋겠습니다.

이 목적지로 도착하는 것을 코어의 메뉴에도 제공하려고 합니다.
바로가기 형태로 주소로 링크를 해야 하는데 이 경우도 고려가 되어있다면 알려주시고
만약 그렇지 않다면 대응을 부탁드립니다.

**Comment by bjrambo** [comment]
`domain.com/index.php?mid=profile&smember={옵션에 따라 닉네임 or member_srl or user_id}&view_type=followinglist`
위의 링크가 기본적인 링크입니다. 따라서,

'getUrl('','mid','midname','smember', '{옵션에 따라 닉네임 or member_srl or user_id}', 'view_type', 'followinglist')` 으로 링크 만드시면 될 것 같습니다.

**Comment by Clouds101** [comment]
관리자 -> 구독 설정 "구독자수 클릭시" 값을 "추가"로 해두면 다른 사람이 나를 팔로워 하고 있는 회원의 목록을 노출 하지 않습니다.

**Comment by wookho** [comment]
@bjrambo  저희는 로그인한 회원 각자에게만 자신이 팔로우한 회원의 명단을 공개하는 서로 누구를 팔로우한 지 알 수 없게 보안을 철저히 하고 있습니다.

안내해주신 링크의 경우 로그인 한 회원은 무조건 자신이 팔로우한 회원의 글을 볼수 잇는 건지요?

**Comment by bjrambo** [comment]
@wookho 위의 @Clouds101 님의 옵션을 사용하신다면 말씀하신대로 구현은 가능할 듯합니다.

**Comment by wookho** [comment]
@Clouds101 팔로우회원의 목록을 보여주지 않는 것은 알고 있습니다.

구독모듈을 구매한 가장 큰 이유가 내가 팔로우한 회원의 글을 모아서 볼 수 있다는 것 때문이었습니다.

@bjrambo 님이 안내주신 링크가 그 방법인가요?

**Comment by bjrambo** [comment]
@wookho 넵 해당 방법대로 해주시면 됩니다.

**Comment by wookho** [comment]
@bjrambo 로그인한 회원에게만 허락되는 뷰 인가요?? 다른 사람이 절대로 글 목록을 봐서는 안됩니다.

**Comment by Clouds101** [comment]
@wookho 안보입니다
직접 확인해 보시길 부탁드립니다.

**Comment by wookho** [comment]
@Clouds101 모듈이 정상동작하지 않아 아직 확인 못하고 있습니다.
패치되면 테스트 해 보겠습니다.

**Comment by wookho** [comment]
@bjrambo @Clouds101 그리고 안내해준 링크를 XE코어에서 제공하는 메뉴에 적용 불가능해 보이는데 로그인한 회원의 닉네임을 변수로해서 메뉴에서 이게 가능한가요?

**Comment by Clouds101** [comment]
<a href="{getUrl('','mid','설정mid','smember',$logged->member_srl,'view_type','followinglist' ) }">내가 팔로잉 하고 있는 사람들의 글 모아 보기</a>
이렇게 레이아웃,스킨에 추가해 주시면 내가 구독하고 있는 회원들의 목록을 나만 볼수 있습니다.

**Comment by wookho** [comment]
@Clouds101 메뉴로도 제공해야 해서요.

**Comment by Clouds101** [comment]
@wookho 링크를 저렇게 해주시면 됩니다.

**Comment by wookho** [comment]
@Clouds101 메뉴 생성시 바로가기로 하고 주소를 저렇게 넣어주면 된다는건가요?

**Comment by bjrambo** [comment]
@wookho 메뉴생성엔 어떠한 변수 사용불가능합니다 (바로가기 링크기준)

**Comment by wookho** [comment]
@bjrambo @Clouds101 사이트 메뉴에서 제공하는 방법은 불가능하고 앞으로 제공할 계획이 없는건가요?

회원전용메뉴에 노출하려고 합니다.

**Comment by bjrambo** [comment]
메뉴로는 어떠한 $logged_info 변수 같은 내용을 함께 링크 할 수 없으며, 썸띵모듈에서 사용하는 smember 의 역활이 비중하기 때문에 커스텀으로 따로 고치지 않는 이상 저희가 지원해드리고자 하는 부분은 어려워 보일 것 같습니다..ㅠ

메뉴형태가 아닌 스킨을 사용하시는 방향으로 가주시는 것이 더 좋겠습니다.

**Comment by wookho** [comment]
@bjrambo 최소한 기본적인 접근주소는 모듈에서 제공해야 하는 거 아닌가요? 
https://도메인/index.php?mid=profile
위 링크가 그 기능을 대신해서 로그인한 회원에게는 
자신의 활동내역(팔로우회원 글목록포함) 을 제공하는 페이지가 열리게 되는 페이지로요.

그래야 메뉴에서 이 부분을 링크걸어 모든 사이트에서 적극 비회원 회원에게 어필할 수 있을 것 같은데요.

비회원이 클릭시에는 회원에게 제공하는 서비하라고 출력해주고요.

**Comment by Clouds101** [comment]
@wookho 
http(s)://xeurl/index.php?mid=설정mid
입력시 컨텐츠를 출력하는 기능은 개발 계획이 없습니다.

**Comment by wookho** [comment]
@Clouds101 
제공 계획이 없으시니 자료를 이용해야 하는 입장에서는 메뉴에서는 제공하지 못하겠군요.
알겠습니다. 대단히 아쉬운 부분이네요.

회원에게 기능을 쉽게 알릴 수 있는게 메뉴로 제공하는 것인데... 운영자로서 개발능력이 없는게 아쉬울 뿐 입니다.
