### ISSUE TITLE
내 팔로우 회원들 글 목록 보기시...

### ISSUE THREAD

**Issue by wookho** [ramboclouds/xe-something#11]
https:/도메인index.php?mid=profile&smember=%EB%AA%BD%EC%8B%A4%EC%95%84%EB%B9%A0&view_type=followinglist

이렇게 제공하면 내가 팔로우한 회원의 글 목록이 나오는 것 확인했습니다.

하지만 스킨에서 팔로우한회원의 글목록 탭을 컨트롤 하다보니..

위 링크로 접근시 상단의 탭이 사라져서 회원에게 제공할 시 약간 문제점이나 어색함 그리고 해당 화면에서 탭을 클릭시 처음에 봤던 화면을 잃게 되는 문제가 있습니다.

스킨의 설정과 상관없이 이 메뉴로 회원 본인이 접속할시에는 스킨에서 노출하지 않았어도 탭이 노출되어야 할 것 같습니다.

**Comment by Clouds101** [comment]
해당 메뉴는 스킨에서 켜두더라도 본인에게만 노출 됩니다.
다른 회원 정보에 접근시 노출되지 않으니 스킨 설정에서는 출력 하도록 설정하시면 될듯합니다.

**Comment by wookho** [comment]
@Clouds101 그럼 그게 내가 보고 있는 회원의 팔로우회원들의 글목록이 아니고
클릭한사람(로그인한사람)의 팔로우회원들의 글 목록인가요?

**Comment by wookho** [comment]
@Clouds101 아닌데요. 방금 노출 시켜 봤더니 
회원들 팔로우로인 한 글목록이 노출되서 개개인이 누구를 팔로우했는지 알게 됩니다.

**Comment by Clouds101** [comment]
내가 구독한 사람들의 글 목록이 출력되며 나에게만 메뉴가 노출됩니다.

**Comment by wookho** [comment]
아.. 제것이 보여서 다른 사람에게 보이는 줄 알았는데 다른 회원의 것을 한번 봐야겠네요.

**Comment by wookho** [comment]
그러네요. 클릭한 사람의 팔로우 명단으로 글 목록을 보여주는 것으로 확인했습니다. 
이와 관련된 추천한 글은 작성자와 같은 사람 기준인거죠?

추천한글에 오류가 있어 새로 이슈로 등록하겠습니다.
