### ISSUE TITLE
다른 회원에게 팔로우회원 글목록 보안이 되는지 확인차...

### ISSUE THREAD

**Issue by wookho** [ramboclouds/xe-something#12]
다른 회원의 닉네임을 넣고 접근해 보았습니다.

Fatal Error: Uncaught Error: Call to undefined function lang() in /home/wookho/public_html/modules/something/something.view.php:173 Stack trace: #0 /home/wookho/public_html/classes/module/ModuleObject.class.php(443): somethingView->dispSomethingProfileView() #1 /home/wookho/public_html/classes/module/ModuleHandler.class.php(844): ModuleObject->proc() #2 /home/wookho/public_html/index.php(63): ModuleHandler->procModule() #3 {main} thrown

**Comment by wookho** [comment]
비로그인 시 접근하면

Fatal Error: Uncaught Error: Call to undefined function lang() in /home/wookho/public_html/modules/something/something.view.php:166 Stack trace: #0 /home/wookho/public_html/classes/module/ModuleObject.class.php(443): somethingView->dispSomethingProfileView() #1 /home/wookho/public_html/classes/module/ModuleHandler.class.php(844): ModuleObject->proc() #2 /home/wookho/public_html/index.php(63): ModuleHandler->procModule() #3 {main} thrown

**Comment by bjrambo** [comment]
#9

**Comment by Clouds101** [comment]
1.0.2 버전에서 오류가 해결 되었습니다.
