### ISSUE TITLE
서명이 길면 프로필이미지 영역으로 

### ISSUE THREAD

**Issue by wookho** [ramboclouds/xe-something#13]
서명이 프로필이미지 영역까지 사용해서 프로필이미지에 서명이 가리게 됩니다.

**Comment by Clouds101** [comment]
스킨 관리 -> 프로필 설정 -> 서명 길이에서 값을 입력해 넘어가지 않도록 조절해 주세요.

**Comment by wookho** [comment]
@Clouds101 공간이 충분해서 서명을 모두 출력하려고 합니다. 이게 프로필이미지를 위해 값을 조정해야 하는건 넌센스 아닌가요?

**Comment by wookho** [comment]
서명출력하는 곳에

프로필이미지 사이즈로 지정하신 80px 보다 조금 여유있게
margin-right: 90px;

로 해주시면 해결될 문제일 것 같습니다.
