### ISSUE TITLE
짧은 주소 http(s)://URL/@user 이용하기 문의

### ISSUE THREAD

**Issue by wookho** [ramboclouds/xe-something#17]
RewriteRule ^@([a-zA-Z0-9_]+)/?$ ./index.php?mid=profile&act=dispSomethingProfileView&smember=$1 [L,QSA]

이렇게 .htacces 파일의 마지막에 추가해 주었습니다.

저희 mid 설정은 profile 로 되어 있는 상태이구요.
아파치 입니다.

The requested URL /@ëª½ì‹¤ì•„ë¹  was not found on this server.

닉네임으로 설정해서 사용하고 있습니다.

**Comment by bjrambo** [comment]
```
RewriteRule ^@([a-zA-Z0-9가-힇_]+)/?$ ./index.php?mid=profile&act=dispSomethingProfileView&smember=$1 [L,QSA]
```
으로 수정해보시고 결과 알려주세요.

**Comment by wookho** [comment]
@bjrambo 잘됩니다~

**Comment by bjrambo** [comment]
@wookho 한글먼저 나오고 뒤에 영어로 이루어진 닉네임에 대해서도 테스트해봐주세요
`람보fkaqh` 형태로요.

**Comment by wookho** [comment]
@BJ람보 <<- 이거로 테스트했습니다. 잘되네요.

골뱅이8포니8  <<<- 요런 숫자도 잘되네요.

**Comment by bjrambo** [comment]
@wookho 확인감사합니다.

**Comment by wookho** [comment]
@bjrambo 
다롱다롱0313 요청하신 한글 먼저 나오는 것도 이상없습니다.
