### ISSUE TITLE
모바일 일단 서명부분 수정이 필요해 보입니다.

### ISSUE THREAD

**Issue by wookho** [ramboclouds/xe-something#18]
모바일 스킨은 최종적으로는 많이 수정이 필요해 보이긴 합니다.

우선 급한대로 서명부분이 문제가 됩니다.

![screenshot_20180319-145632](https://user-images.githubusercontent.com/6590236/37580330-7ccc1c54-2b86-11e8-9c4a-ababfabfb0e0.png)

**Comment by Clouds101** [comment]
1.0.4 버전에서 css class 가 상당 부분 수정 되었습니다.
업데이트후 확인 부탁 드리겠습니다.
