### ISSUE TITLE
추천한 글 출력 갯수가 중복 출력됩니다.

### ISSUE THREAD

**Issue by wookho** [ramboclouds/xe-something#20]
어떤 기준으로 중복해서 출력되는지 모르겠는데요.
여러개가 반복출력됩니다.

**Comment by Clouds101** [comment]
테스트를 해보았는데 문제가 없는것 같습니다.
xe_document_voted_log 테이블에 중복 출력되는 회원의 기록을 확인해주시길 부탁드리겠습니다.

**Comment by Clouds101** [comment]
phpmyadmin 등 sql 관리툴에서 쿼리는 `select * FROM xe_document_dovted_log WHERE member_srl = 회원SRL번호 and point=1`

**Comment by wookho** [comment]
일단 저희는 추천정보를 제공하지 않아 옵션에서 사용하지 않고 있습니다. 
이상현상 제보를 위해 이슈등록했습니다. 필요없다면 닫으셔도 됩니다.
저희는 모든 글이 일정한 패던 없어 6회 5회 이런식으로 중복 출력되고 있으니 이점 참고해주세요.
