### ISSUE TITLE
익명으로 작성된 글에 대해서는 작성 글/댓글 목록에 포함되지 않아야 합니다.

### ISSUE THREAD

**Issue by fyrate** [ramboclouds/xe-something#21]
현재 익명으로 작성된 게시글/댓글에 대해서도 작성 글/댓글 목록에 수집이 되고 있습니다.

이는 사이트의 익명성을 보장하지 못하는 문제로 직결하여

익명 게시판이 있는 사이트에서는 something을 사용하기가 어려울 수 있는 문제점이 있습니다.

**Comment by bjrambo** [comment]
관리자 페이지의 설정에서 익명게시판에 해당되는 게시판을 사용을 해제할 수 있도록 되어있습니다. 이 부분의 옵션을 확인 후 다시 피드백 남겨주세요 :)

**Comment by fyrate** [comment]
제 사이트에는
선택적으로 익명을 사용하는, 반 익명 게시판들이 상당 수 존재하고 있습니다.
개별적으로 게시판을 선택하여야 한다면 해당 게시판들은 포함할 수 없기 때문에 불완전해질 것 같습니다. 코드에 해당 글의 익명여부를 확인해서 익명이 아닌 경우에만 출력하도록 조건문을 걸어주시고, 그에 대한 옵션을 skin.xml에 만들어주셨으면 좋겠습니다.

**Comment by bjrambo** [comment]
저희는 공개 자료의 경우 대부분 XE의 기본 동작에 맞게 선택하여 만들고 있습니다.

비밀글도 아닌, 익명의 경우 XE의 기본 동작은 해당 게시판의 익명으로 선택한 경우 해당 게시판을 선택적이 아닌 항상 익명을 쓰는 경우로 보기 때문에 저희가 따로 옵션을 추가하지 않은 것입니다.

이 부분의 경우 따로 커스텀 의뢰를 진행을 하시는 것이 좋겠습니다.(_ _ )

https://xe-something.com/request
