### ISSUE TITLE
추천한 글 보기에 대해서 사용/미사용 옵션이 있으면 좋겠습니다.

### ISSUE THREAD

**Issue by fyrate** [ramboclouds/xe-something#22]
사이트 회원들의 전체적인 성향이 본인이 추천한 글에 대해서 남에게 알리고 싶지 않아하는
성향이라면 이 모듈로 인해서 추천을 오히려 하지않게 되는 결과가 나올 수 있을 것 같습니다.

이 부분 옵션에 추가가 되면 좋을 것 같습니다.

**Comment by Clouds101** [comment]
스킨 관리에서 해당 메뉴를 끄고 켤수 있습니다.
