### ISSUE TITLE
1.0.5 업데이트 후 목록에서 글 작성시간 미출력

### ISSUE THREAD

**Issue by wookho** [ramboclouds/xe-something#23]
PC와 모바일 모두 작성시간이 표시되지 않습니다.

**Comment by wookho** [comment]
작성글 목록에서는 표시가 되네요.

팔로우 글 의 목록에서 작성시간이 표시되지 않고 있습니다.

**Comment by Clouds101** [comment]
1.0.7 업데이트에 반영 되었습니다.

**Comment by wookho** [comment]
@Clouds101 업데이트 후 잘 나오네요.
