### ISSUE TITLE
작성시간 에 분 이하는 생략했으면 합니다.

### ISSUE THREAD

**Issue by wookho** [ramboclouds/xe-something#24]
초단위 까지 표시하지 않아도 충분할 것 같습니다.
특히 모바일의 경우 지면이 협소하다보니 이 분 이하 초단위를 표시하는 부분의 길이가 상당히 차지하네요.

**Comment by bjrambo** [comment]
해당 부분은 XE변수를 통해서 처리하고 있습니다.

https://github.com/ramboclouds/xe-something/blob/master/skins/timeline/profile.html#L2

대부분 이렇게 함수 구현으로 만들어져 있습니다..

**Comment by wookho** [comment]
@bjrambo
"Y.m.d H:i:s"

이부분에서 초 단위까지 표시되는군요. 저는 댓글 출력 부분에서 너무 길어 백분의 일초 까지 나오는 줄 착각한 모양입니다.
그런데 4자리년도 .월.일. 시:분:초 

이렇게 나오니 너무 길어지는 것 같습니다.

제목에 분이하 생략을 시간을 생략하는 것으로 바꾸면 될 것 같습니다.

XE에서는 24시간 이후 시간이 아닌 날짜로 바뀌는데...  오래된 글의 경우 날짜 까지만 나와도 좋을 것 같습니다. 물론 PC에서는 자리가 충분해서 괜찮긴 한데요...

**Comment by bjrambo** [comment]
`Y.m.d H:i:s` 부분을 찾으셔서 마지막 `:s` 부분만 삭제 해주셔도 될듯 합니다

**Comment by wookho** [comment]
@bjrambo
그렇겠죠. 저는 대부분의 사람이 불편할 듯 하여 제보를 드리는 것입니다. 제가 삭제 할 수는 있겠죠.
제 판단은 제가 처음에 초이하가 긴 것으로 착각하고 이슈를 남겼지만..

댓글 달아주신 것 보고 다시 확인해 보니 년도월일시분초 자체가 길더군요. 
개인적으로 처리 한다면 이후 스킨 수정이 거의 없는 안정화 이후에
년도월일 까지만 출력되게 처리하겠습니다.
