### ISSUE TITLE
모바일 오른쪽 여백이 생기면서 화면이 가로 스크롤 됩니다.

### ISSUE THREAD

**Issue by wookho** [ramboclouds/xe-something#29]
![screenshot_20180320-105522](https://user-images.githubusercontent.com/6590236/37631555-8a058886-2c2d-11e8-9fd9-961bd294aa7d.png)

원인을 찾아보려고 했는데 쉽지 않네요.
뒤에 구독모듈이 없을 경우 멘트가 출력되는 곳도 영역을 벗어 나는데요. 그것 때문인지는 확인하지는 못했습니다.

스크린샷 과 같은 공간이 존재하고 처음 열렸을때는 눈치를 못채는데 화면을 건드리다 보면 가로로 스크롤이 됩니다.

제가 확인한 다른 사이트는 글 목록의 컨텐츠 안에 링크주소가 길게 있으면 그것이 레이아웃 영역을 넘어가고 넘어간 만큼 우측에 공백이 생기고 가로 스크롤이 그만큼 됩니다.

**Comment by Clouds101** [comment]
이 문제와 관련하여 1.0.8 에서 개선이 있습니다.
업데이트후 확인 부탁드립니다.

**Comment by wookho** [comment]
저희 사이트에서 발견되었던 여백이 생기고 가로 스크롤로 이동이 되는게 개선이 되었네요.
컨텐츠가 벗어나는건 저희 사이트에 발생하지 않아 확인하지는 못했습니다.
