### ISSUE TITLE
팔로우 글 1페이지가 팔로우 하지 않은 사람의 글이 나타납니다. 

### ISSUE THREAD

**Issue by garnecia** [ramboclouds/xe-something#31]
찾아보니

something.model.php 214번줄

**$sObj->member_srls** = implode($member_srls, ",");

로 되어있습니다. **$sObj->member_srl**로 바꿔주니 잘 해결되었습니다.

**Comment by Clouds101** [comment]
오류 제보 감사드립니다.
1.0.8 에서 수정 되었습니다.
