### ISSUE TITLE
추천한 글 보기시에 같은 글이 여러개 보입니다.

### ISSUE THREAD

**Issue by clamp2x** [ramboclouds/xe-something#33]
![image](https://user-images.githubusercontent.com/28799752/37673651-1a179820-2cb4-11e8-9316-6521e865cca4.png)

이런 식으로 추천한 글이 한번만 보이는게 아니라 여러번 보입니다.
링크를 통해 확인해보실 수도 있습니다.
https://studyforus.com/index.php?mid=something&smember=%EB%A7%88%EC%8A%A4%ED%84%B0&view_type=recommend

혹시라도 제가 설정을 잘못한걸까요?

**Comment by Clouds101** [comment]
혹시 추천기능 관련해서 커스터마이징 하신게 있으신가요?

xe_document_voted_log 테이블에 중복 출력되는 회원의 기록을 확인해주시길 부탁드리겠습니다.
phpmyadmin 등 sql 관리툴에서 아래와 같은 쿼리로 실제 데이터들은 어떻게 나오는지 확인 부탁 드립니다.
`select * FROM xe_document_dovted_log WHERE member_srl = 회원SRL번호 and point=1`

**Comment by clamp2x** [comment]
추천 기능에 대해서 별도로 커스터마이징 하지는 않았습니다.
라이믹스 사용중인데 최근 라이믹스에서는 추천 기능이 추천자에게도 포인트를 줄 수 있게끔 업데이트 되었습니다. 그게 원인인지 모르겠습니다.

또한 DB에서 위의 쿼리를 돌렸을 때
한 회원의 srl의 추천 내역을 살펴보면 한 문서srl에 여러번 중복이 되도록 추천이 된 로그는 없었습니다.
즉, 한 문서 srl 당 회원 srl 한번씩입니다.

그리고, select * FROM xe_document_dovted_log WHERE member_srl = 회원SRL번호 and point=1
쿼리문 중에 xe_document_dovted_log 부분이 원래는 xe_document_**voted**_log 맞죠?
xe_document_voted_log 로 쿼리 돌려서 확인했습니다.

**Comment by Clouds101** [comment]
something.model.php
141 라인위에 코드를 추가후 테스트를 부탁 드립니다.

//변경전
return $output;

//변경후
$output->data = $documents; // 추가된 항목
return $output;

**Comment by wookho** [comment]
@clamp2x 라이믹스만의 문제는 아닐겁니다. 제가 같은 문제로 이슈를 먼저 등록했었습니다.

**Comment by clamp2x** [comment]
@Clouds101 위에 내용대로 적용해보니 정상적으로 추천내역이 보여집니다.
이대로 버그 수정해주시면 될 것 같습니다.

@wookho 여기 이슈 부분에서 같은 이슈가 있나 찾아봤는데 제가 못봤나봐요.
위에 내용대로 수정하니 정상적으로 작동합니다.

**Comment by wookho** [comment]
@clamp2x 제가 등록한 이슈는 close 되었어요. 못보셨을 겁니다.

**Comment by clamp2x** [comment]
@wookho 그렇네요. closed 되어 있네요.
곧 패치가 될것 같습니다.
