### ISSUE TITLE
내가 팔로잉 하는 회원들의 글 모음 타임라인 페이지

### ISSUE THREAD

**Issue by wookho** [ramboclouds/xe-something#5]
배포된 후 어떻게 구성된건지 확인하고 피드백을 드리는 것 보다 사전에 어느정도 의견을 드리는 것도 좋을 것 같아 의견을 드립니다.

구름이님 구독모듈을 위한 별도 자료를 제공하지 않고 이 모듈에 구독모듈을 연동하는 방식이라 불가피하게 유료자료의 기능에 대한 요청을 이쪽으로 드립니다.

아시다시피 커뮤니티에서 서로의 팔로워,팔로잉 을 알게 되면 누구 누구를 좋아하고 누구는 싫어하고 등의 정보가 제공되어 해당 명단노출을 관리자가 결정할 수 있도록 했습니다.

섬띵모듈도 똑같은 보안이 필요한데요.

회원활동보기에 여러 탭이 제공될 것으로 예상이 됩니다.

작성글/코멘트/추천한글 

현재 미리 알려주신 스크린샷에서는 이정도 보였습니다. 
여기서 추천한글 의 경우도 선호하는 글이 어떤 글인지 이사람의 성향이 어떤 성향인지 파악되는 정보로서 민감한 정보로 아마 관리자가 정 할 것 입니다.

여기에 제가 오늘 요청을 드리고 싶은 것은...

혹시 회원들이 팔로잉하고 있는 사람들의 글을 모아서 보여주는 것도 저기에 탭으로 붙이실 것인지 궁금합니다. 저희는 만약 그렇다면 출력을 하지 않게 될 것 같구요.

실제적으로 구독모듈을 구매한 사이트의 경우 본인만 본인의 팔로잉 회원들의 글을 모아서 타임라인 형식의 별도 화면을 보여주고 싶을 것 입니다. 

해당 페이지와 연결될 수 있는 주소가 제공되고 해당주소를 클릭하면 내가 팔로잉 한 사람들의 글 들이 트위터 처럼 최근글부터 나열이 되어 있는 것이죠.

해당 링크 노출은 비회원에게도 어필을 하고자 노출해 놓았다면 비회원이 클릭시 "로그인이 필요한 서비스입니다." 라고 출력이 될 것이고..

회원이 클릭시 해당회원이 팔로잉한 회원의 글을 뿌려주는 화면으로 전환이 되는 것 입니다.

모든 회원의 자기중심에서 sns 페이지가 생긴다고 보시면 됩니다. 여기에는 여러 회원들의 글 목록만 있는 것이죠. 

그리고 회원이 이 주소를 통해 남의 팔로잉 현황을 알고 싶어 주소에 다른회원의 닉네임이나 회원번호를 넣고 글 목록을 보려고 시도한다면 이건 차단이 되어야 하구요.

혹시 생각하신 것과 저희가 원하는 것과 많이 다르지 않았으면 해서 미리 의견을 드려보았습니다.

**Comment by Clouds101** [comment]
팔로우 모듈 관련해서 보안 기능이 제작되어 있습니다.
지금은 베타 테스트 중이며 배포를 위해 별도 사이트를 제작중입니다.

**Comment by bjrambo** [comment]
필요하신경우 develop 브랜치를 미리 받으셔서 설치하신다음 테스트 해보시면 됩니다. ㅎㅎ

다만, 배포전에는 메뉴얼이나 등등 제공이 어려워서 문제가 있는 부분의 버그성의 제보만 받고 저희가 의도한 바의 내용을 재대로 그때그때 바로바로 피드백은 추후 받을 예정이에요.

**Comment by wookho** [comment]
@bjrambo 네. 필요하다면 미리 해볼 수 도 있는데 일단 배포하시면 설치할 생각으로 기다리고 있어요.
아무쪼록 팔로우(구독)모듈이 좀더 회원들에게 어필 될 수 있도록 만들어졌으면 합니다. 작년부터 팔로우! 해 두면 좋은일 생긴다고 이야기 해 놓았는데 이제 관리자가 꾸며 놓은 글목록 말고 회원들이 보고싶은 글목록을 구성할 수 있다면 회원들에게는 정말 좋은 일 일겁니다.
